[package]
name = "shader"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["dylib", "rlib"]

[dependencies]
shared = { path = "../shared" }
spirv-std = { workspace = true }
prim = { path = "../prim" }
world = { path = "../world", default-features = false }

[dev-dependencies]
tree64 = { path = "../tree64" }
bytemuck = { workspace = true }

[lints]
workspace = true
